# Generated by Django 5.0.2 on 2024-02-21 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ish_Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ish_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('mahsulot_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='missed_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Xatolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('xato_id', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('bulim_id', models.CharField(max_length=9, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Null', 'Null')], default='Null', max_length=10)),
                ('photo', models.ImageField(default='base.jpg', upload_to='xodim_photo/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('id_raqam', models.CharField(max_length=9, unique=True)),
                ('bulimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodim_bulim', to='xodim.bulim')),
                ('ish_turi', models.ManyToManyField(related_name='xodim_ish_turi', to='xodim.ish_turi')),
            ],
        ),
        migrations.CreateModel(
            name='Missed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_soni', models.PositiveIntegerField(default=0)),
                ('butun_soni', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='missed_audio/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_mahsulot', to='xodim.mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_user', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ManyToManyField(related_name='missed_photo', to='xodim.photo')),
                ('xato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_xato', to='xodim.xatolar')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_xodim', to='xodim.xodim')),
            ],
        ),
    ]
